name: Metrics

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.GIT_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: count,percentage
          plugin_reactions_ignored: bot
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
#          plugin_wakatime: yes
#          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}      # Required
#          plugin_wakatime_days: 7                                   # Display last week stats
#          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
#          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
